### ISSUE TITLE
PaintJob prevents dyeing the vanilla way

### ISSUE THREAD

**Issue by michaelarlt** [Laotseu/7dtdMods#3]
The file item_modifiers.xml causes an issue with the way you would dye any vehicle the vanilla way. I do understand you want to prevent the blinking dye, so players wont be confused even if the dye cannot be applied to your customized vehicles. But this does make the vanilla dyeing useless for all vehicle modlets.

**Comment by Laotseu** [comment]
Code removed in PaintJob v2.1
